FROM node:22 AS build

WORKDIR /app
COPY web .
RUN corepack install
RUN corepack enable
RUN pnpm install
RUN pnpm build

FROM node:22

WORKDIR /app

COPY --from=build /app/.output ./

EXPOSE 3000

CMD ["node","/app/server/index.mjs"]
