FROM rust:1.87.0 AS builder

WORKDIR /app
COPY . .
RUN apt update && apt install -y libssl-dev
RUN cargo build --release --bin api

FROM debian:bookworm-slim
# Install openssl
RUN apt update && apt install -y libssl3 && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/api /api

EXPOSE 8080
CMD ["/api"]
