/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`auth_fastly_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthFastlyTokenError {
    Status400(models::BadRequest400Response),
    Status401(models::Unauthorized401Response),
    Status412(models::PreconditionFailed412Response),
    Status422(models::UnprocessableEntity422Response),
    Status503(models::Maintenance503Response),
    Status500(models::InternalServerError500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`auth_login`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthLoginError {
    Status400(models::AuthLogin400Response),
    Status403(models::AuthLogin403Response),
    Status412(models::PreconditionFailed412Response),
    Status422(models::UnprocessableEntity422Response),
    Status503(models::Maintenance503Response),
    Status500(models::InternalServerError500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`auth_logout`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthLogoutError {
    Status400(models::BadRequest400Response),
    Status401(models::Unauthorized401Response),
    Status412(models::PreconditionFailed412Response),
    Status422(models::UnprocessableEntity422Response),
    Status503(models::Maintenance503Response),
    Status500(models::InternalServerError500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`auth_refresh`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthRefreshError {
    Status400(models::AuthRefresh400Response),
    Status401(models::AuthRefresh401Response),
    Status403(models::AuthRefresh403Response),
    Status412(models::PreconditionFailed412Response),
    Status422(models::UnprocessableEntity422Response),
    Status503(models::Maintenance503Response),
    Status500(models::InternalServerError500Response),
    UnknownValue(serde_json::Value),
}

pub async fn auth_fastly_token(
    configuration: &configuration::Configuration,
    locale: &str,
    operating_system: Option<&str>,
    application_version: Option<&str>,
    debug_time_delta_seconds: Option<&str>,
    debug_maintenance_mode: Option<i64>,
) -> Result<models::FastlyTokenResponse, Error<AuthFastlyTokenError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_locale = locale;
    let p_operating_system = operating_system;
    let p_application_version = application_version;
    let p_debug_time_delta_seconds = debug_time_delta_seconds;
    let p_debug_maintenance_mode = debug_maintenance_mode;

    let uri_str = format!(
        "{}/{locale}/auth/fastly/token",
        configuration.base_path,
        locale = crate::apis::urlencode(p_locale)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_debug_maintenance_mode {
        req_builder = req_builder.query(&[("debug_maintenance_mode", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_operating_system {
        req_builder = req_builder.header("Operating-System", param_value.to_string());
    }
    if let Some(param_value) = p_application_version {
        req_builder = req_builder.header("Application-Version", param_value.to_string());
    }
    if let Some(param_value) = p_debug_time_delta_seconds {
        req_builder = req_builder.header("Debug-Time-Delta-Seconds", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FastlyTokenResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FastlyTokenResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AuthFastlyTokenError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn auth_login(
    configuration: &configuration::Configuration,
    locale: &str,
    operating_system: Option<&str>,
    application_version: Option<&str>,
    debug_time_delta_seconds: Option<&str>,
    debug_maintenance_mode: Option<i64>,
    post_auth_login_request: Option<models::PostAuthLoginRequest>,
) -> Result<models::PostAuthLoginResponse, Error<AuthLoginError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_locale = locale;
    let p_operating_system = operating_system;
    let p_application_version = application_version;
    let p_debug_time_delta_seconds = debug_time_delta_seconds;
    let p_debug_maintenance_mode = debug_maintenance_mode;
    let p_post_auth_login_request = post_auth_login_request;

    let uri_str = format!(
        "{}/{locale}/auth/login",
        configuration.base_path,
        locale = crate::apis::urlencode(p_locale)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_debug_maintenance_mode {
        req_builder = req_builder.query(&[("debug_maintenance_mode", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_operating_system {
        req_builder = req_builder.header("Operating-System", param_value.to_string());
    }
    if let Some(param_value) = p_application_version {
        req_builder = req_builder.header("Application-Version", param_value.to_string());
    }
    if let Some(param_value) = p_debug_time_delta_seconds {
        req_builder = req_builder.header("Debug-Time-Delta-Seconds", param_value.to_string());
    }
    req_builder = req_builder.json(&p_post_auth_login_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostAuthLoginResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostAuthLoginResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AuthLoginError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn auth_logout(
    configuration: &configuration::Configuration,
    locale: &str,
    operating_system: Option<&str>,
    application_version: Option<&str>,
    debug_time_delta_seconds: Option<&str>,
    debug_maintenance_mode: Option<i64>,
) -> Result<(), Error<AuthLogoutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_locale = locale;
    let p_operating_system = operating_system;
    let p_application_version = application_version;
    let p_debug_time_delta_seconds = debug_time_delta_seconds;
    let p_debug_maintenance_mode = debug_maintenance_mode;

    let uri_str = format!(
        "{}/{locale}/auth/logout",
        configuration.base_path,
        locale = crate::apis::urlencode(p_locale)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_debug_maintenance_mode {
        req_builder = req_builder.query(&[("debug_maintenance_mode", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_operating_system {
        req_builder = req_builder.header("Operating-System", param_value.to_string());
    }
    if let Some(param_value) = p_application_version {
        req_builder = req_builder.header("Application-Version", param_value.to_string());
    }
    if let Some(param_value) = p_debug_time_delta_seconds {
        req_builder = req_builder.header("Debug-Time-Delta-Seconds", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AuthLogoutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn auth_refresh(
    configuration: &configuration::Configuration,
    locale: &str,
    operating_system: Option<&str>,
    application_version: Option<&str>,
    debug_time_delta_seconds: Option<&str>,
    debug_maintenance_mode: Option<i64>,
    post_auth_refresh_request: Option<models::PostAuthRefreshRequest>,
) -> Result<models::PostAuthRefreshResponse, Error<AuthRefreshError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_locale = locale;
    let p_operating_system = operating_system;
    let p_application_version = application_version;
    let p_debug_time_delta_seconds = debug_time_delta_seconds;
    let p_debug_maintenance_mode = debug_maintenance_mode;
    let p_post_auth_refresh_request = post_auth_refresh_request;

    let uri_str = format!(
        "{}/{locale}/auth/refresh",
        configuration.base_path,
        locale = crate::apis::urlencode(p_locale)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_debug_maintenance_mode {
        req_builder = req_builder.query(&[("debug_maintenance_mode", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_operating_system {
        req_builder = req_builder.header("Operating-System", param_value.to_string());
    }
    if let Some(param_value) = p_application_version {
        req_builder = req_builder.header("Application-Version", param_value.to_string());
    }
    if let Some(param_value) = p_debug_time_delta_seconds {
        req_builder = req_builder.header("Debug-Time-Delta-Seconds", param_value.to_string());
    }
    req_builder = req_builder.json(&p_post_auth_refresh_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostAuthRefreshResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostAuthRefreshResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AuthRefreshError> = serde_json::from_str(&content).ok();
        dbg!(ResponseContent {
            status,
            content: content.clone(),
            entity: entity.clone(),
        });
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
