/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Announcement {
    /// おしらせID
    #[serde(rename = "id")]
    pub id: String,
    /// 掲載開始日時
    #[serde(rename = "opened_at")]
    pub opened_at: i64,
    /// タイトル
    #[serde(rename = "title")]
    pub title: String,
    /// おしらせ本文
    #[serde(rename = "body")]
    pub body: String,
    /// 重要なお知らせかどうか
    #[serde(rename = "is_important")]
    pub is_important: bool,
    /// お知らせ詳細のWebURL
    #[serde(rename = "detail_url")]
    pub detail_url: String,
}

impl Announcement {
    pub fn new(
        id: String,
        opened_at: i64,
        title: String,
        body: String,
        is_important: bool,
        detail_url: String,
    ) -> Announcement {
        Announcement {
            id,
            opened_at,
            title,
            body,
            is_important,
            detail_url,
        }
    }
}
