/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentLinkGroupEventSchedules : リンクするグループ任天堂イベントスケジュールID. 存在しない場合は空文字
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentLinkGroupEventSchedules {
    #[serde(
        rename = "group_event_schedule_id",
        skip_serializing_if = "Option::is_none"
    )]
    pub group_event_schedule_id: Option<String>,
    #[serde(rename = "event_schedules", skip_serializing_if = "Option::is_none")]
    pub event_schedules: Option<Vec<models::EventSchedule>>,
}

impl ContentLinkGroupEventSchedules {
    /// リンクするグループ任天堂イベントスケジュールID. 存在しない場合は空文字
    pub fn new() -> ContentLinkGroupEventSchedules {
        ContentLinkGroupEventSchedules {
            group_event_schedule_id: None,
            event_schedules: None,
        }
    }
}
