/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentRating : レーティング
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentRating {
    /// コンテンツパネル用のアイコンURL
    #[serde(rename = "icon_url")]
    pub icon_url: String,
    /// (deprecated) コンテンツパネル用のアイコンのheight(px)
    #[serde(rename = "icon_url_height")]
    pub icon_url_height: i64,
    /// (deprecated) コンテンツパネル用のアイコンのwidth(px)
    #[serde(rename = "icon_url_width")]
    pub icon_url_width: i64,
    /// Contents Descriptorの配列
    #[serde(rename = "contents_descriptors")]
    pub contents_descriptors: Vec<String>,
    /// (deprecated) Interactive Elementの配列
    #[serde(rename = "interactive_elements")]
    pub interactive_elements: Vec<String>,
    /// (deprecated) 映像単体型もしくは画像単体型の表示に使うアイコンURL
    #[serde(rename = "icon_url_for_movie_or_image_content")]
    pub icon_url_for_movie_or_image_content: String,
    /// (deprecated) 映像単体型もしくは画像単体型の表示に使うアイコンのheight(px)
    #[serde(rename = "icon_url_for_movie_or_image_content_height")]
    pub icon_url_for_movie_or_image_content_height: i64,
    /// (deprecated) 映像単体型もしくは画像単体型の表示に使うアイコンのwidth(px)
    #[serde(rename = "icon_url_for_movie_or_image_content_width")]
    pub icon_url_for_movie_or_image_content_width: i64,
    /// 動画単体型向けのアイコンURL PEGI / IARC_PEGIの場合、黒背景用の白フレーム画像になります
    #[serde(rename = "icon_url_for_movie_content")]
    pub icon_url_for_movie_content: String,
    /// 動画単体型向けのアイコンのサイズの比率(%)を返します OFLC(AGCB) / OFLC.NZ / PEGI / USK の場合   縦長（16:9）動画の場合30%、正方形（1:1）動画の場合40%、横長（9:16）動画の場合50% ESRB / SMEC / ClassInd / IARC_GENERIC の場合   縦長（16:9）動画の場合20%、正方形（1:1）動画の場合40%、横長（9:16）動画の場合50%
    #[serde(rename = "icon_url_for_movie_content_size_ratio")]
    pub icon_url_for_movie_content_size_ratio: i64,
    /// 動画単体型向けのアイコンのheight(px)
    #[serde(rename = "icon_url_for_movie_content_size_height")]
    pub icon_url_for_movie_content_size_height: i64,
    /// 動画単体型向けのアイコンのwidth(px)
    #[serde(rename = "icon_url_for_movie_content_size_width")]
    pub icon_url_for_movie_content_size_width: i64,
    /// 画像単体型向けのアイコンURL URLがアイコンに含まれるものに関してはURLとアイコン本体を左揃えにした画像になります
    #[serde(rename = "icon_url_for_image_content")]
    pub icon_url_for_image_content: String,
}

impl ContentRating {
    /// レーティング
    pub fn new(
        icon_url: String,
        icon_url_height: i64,
        icon_url_width: i64,
        contents_descriptors: Vec<String>,
        interactive_elements: Vec<String>,
        icon_url_for_movie_or_image_content: String,
        icon_url_for_movie_or_image_content_height: i64,
        icon_url_for_movie_or_image_content_width: i64,
        icon_url_for_movie_content: String,
        icon_url_for_movie_content_size_ratio: i64,
        icon_url_for_movie_content_size_height: i64,
        icon_url_for_movie_content_size_width: i64,
        icon_url_for_image_content: String,
    ) -> ContentRating {
        ContentRating {
            icon_url,
            icon_url_height,
            icon_url_width,
            contents_descriptors,
            interactive_elements,
            icon_url_for_movie_or_image_content,
            icon_url_for_movie_or_image_content_height,
            icon_url_for_movie_or_image_content_width,
            icon_url_for_movie_content,
            icon_url_for_movie_content_size_ratio,
            icon_url_for_movie_content_size_height,
            icon_url_for_movie_content_size_width,
            icon_url_for_image_content,
        }
    }
}
