/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FastlyToken {
    /// (deprecated) 1階層上のtokenを使ってください
    #[serde(rename = "token")]
    pub token: String,
    /// Fastly 認証用トークンを使用するURL。言語コード、国コードのクエリパラメータ を含んでいる。
    #[serde(rename = "url")]
    pub url: String,
}

impl FastlyToken {
    pub fn new(token: String, url: String) -> FastlyToken {
        FastlyToken { token, url }
    }
}
