/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameTitle {
    /// Deepen管理のゲームタイトルID
    #[serde(rename = "id")]
    pub id: String,
    /// タイトル
    #[serde(rename = "title")]
    pub title: String,
    /// サムネイルアイコンのURL
    #[serde(rename = "icon_url", skip_serializing_if = "Option::is_none")]
    pub icon_url: Option<String>,
    /// プラットフォーム名(ローカライズ済み) 複数プラットフォームに対応したソフトの場合、プラットフォーム名を「/」で繋げた文字列を返します
    #[serde(rename = "platform_text")]
    pub platform_text: String,
}

impl GameTitle {
    pub fn new(id: String, title: String, platform_text: String) -> GameTitle {
        GameTitle {
            id,
            title,
            icon_url: None,
            platform_text,
        }
    }
}
