/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPremiere {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    #[serde(rename = "premiere")]
    pub premiere: Box<models::Premiere>,
}

impl GetPremiere {
    pub fn new(user_basic_info: models::UserBasicInfo, premiere: models::Premiere) -> GetPremiere {
        GetPremiere {
            user_basic_info: Box::new(user_basic_info),
            premiere: Box::new(premiere),
        }
    }
}
