/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetContentSeriesInfo : シリーズの情報
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContentSeriesInfo {
    /// シリーズの前話のコンテンツID
    #[serde(
        rename = "prev_content_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub prev_content_id: Option<Option<String>>,
    /// シリーズの次話のコンテンツID
    #[serde(
        rename = "next_content_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_content_id: Option<Option<String>>,
}

impl GetContentSeriesInfo {
    /// シリーズの情報
    pub fn new() -> GetContentSeriesInfo {
        GetContentSeriesInfo {
            prev_content_id: None,
            next_content_id: None,
        }
    }
}
