/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEventSchedulesCalendarsInner {
    /// 日付
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "event_schedules")]
    pub event_schedules: Vec<models::UserEventSchedule>,
    /// 祝日名. 祝日ではない場合は空文字
    #[serde(rename = "holiday")]
    pub holiday: String,
}

impl GetEventSchedulesCalendarsInner {
    pub fn new(
        date: String,
        event_schedules: Vec<models::UserEventSchedule>,
        holiday: String,
    ) -> GetEventSchedulesCalendarsInner {
        GetEventSchedulesCalendarsInner {
            date,
            event_schedules,
            holiday,
        }
    }
}
