/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetFavoriteIpOptionsResponseFavoriteIpOptionsInner : 好きなIPの選択肢
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFavoriteIpOptionsResponseFavoriteIpOptionsInner {
    /// IP
    #[serde(rename = "id")]
    pub id: i64,
    /// IPのアイコンのURL
    #[serde(rename = "icon_url")]
    pub icon_url: String,
    /// IP名
    #[serde(rename = "name")]
    pub name: String,
    /// 好きなIPに設定しているかどうか
    #[serde(rename = "is_favorite")]
    pub is_favorite: bool,
}

impl GetFavoriteIpOptionsResponseFavoriteIpOptionsInner {
    /// 好きなIPの選択肢
    pub fn new(
        id: i64,
        icon_url: String,
        name: String,
        is_favorite: bool,
    ) -> GetFavoriteIpOptionsResponseFavoriteIpOptionsInner {
        GetFavoriteIpOptionsResponseFavoriteIpOptionsInner {
            id,
            icon_url,
            name,
            is_favorite,
        }
    }
}
