/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAnnouncement {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    #[serde(rename = "announcement")]
    pub announcement: Box<models::UserAnnouncement>,
}

impl GetAnnouncement {
    pub fn new(
        user_basic_info: models::UserBasicInfo,
        announcement: models::UserAnnouncement,
    ) -> GetAnnouncement {
        GetAnnouncement {
            user_basic_info: Box::new(user_basic_info),
            announcement: Box::new(announcement),
        }
    }
}
