/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAvailableTags {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    #[serde(rename = "character_tags")]
    pub character_tags: Vec<models::Tag>,
    #[serde(rename = "search_top_game_title_tags")]
    pub search_top_game_title_tags: Vec<models::Tag>,
    #[serde(rename = "all_game_title_tags")]
    pub all_game_title_tags: Vec<models::Tag>,
    #[serde(rename = "platform_tags")]
    pub platform_tags: Vec<models::Tag>,
    #[serde(rename = "other_tags")]
    pub other_tags: Vec<models::Tag>,
    /// さがすTOPでゲームソフト／アプリに「もっとみる」を表示するかどうか
    #[serde(rename = "is_game_tags_show_more")]
    pub is_game_tags_show_more: bool,
}

impl GetAvailableTags {
    pub fn new(
        user_basic_info: models::UserBasicInfo,
        character_tags: Vec<models::Tag>,
        search_top_game_title_tags: Vec<models::Tag>,
        all_game_title_tags: Vec<models::Tag>,
        platform_tags: Vec<models::Tag>,
        other_tags: Vec<models::Tag>,
        is_game_tags_show_more: bool,
    ) -> GetAvailableTags {
        GetAvailableTags {
            user_basic_info: Box::new(user_basic_info),
            character_tags,
            search_top_game_title_tags,
            all_game_title_tags,
            platform_tags,
            other_tags,
            is_game_tags_show_more,
        }
    }
}
