/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSettingCalendarResponseOfficialEventSettingInGameEventSetting : ゲーム内イベントに関連するイベントの設定
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSettingCalendarResponseOfficialEventSettingInGameEventSetting {
    /// ゲーム内イベントの表示設定が有効かどうか
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// 直近３ヶ月でプレイしたゲームの設定
    #[serde(rename = "recent_play_game_titles")]
    pub recent_play_game_titles: Vec<models::GetSettingCalendarResponseOfficialEventSettingInGameEventSettingRecentPlayGameTitlesInner>,
    /// 過去にプレイしたゲームの設定
    #[serde(rename = "past_play_game_titles")]
    pub past_play_game_titles: Vec<models::GetSettingCalendarResponseOfficialEventSettingInGameEventSettingRecentPlayGameTitlesInner>,
    /// その他のゲームの設定
    #[serde(rename = "other_game_titles")]
    pub other_game_titles: Vec<models::GetSettingCalendarResponseOfficialEventSettingInGameEventSettingRecentPlayGameTitlesInner>,
    /// 表示がOFFになる期間で「次にプレイする時まで」を表示するかどうか
    #[serde(rename = "show_until_play_next_button")]
    pub show_until_play_next_button: bool,
}

impl GetSettingCalendarResponseOfficialEventSettingInGameEventSetting {
    /// ゲーム内イベントに関連するイベントの設定
    pub fn new(
        enabled: bool,
        recent_play_game_titles: Vec<models::GetSettingCalendarResponseOfficialEventSettingInGameEventSettingRecentPlayGameTitlesInner>,
        past_play_game_titles: Vec<models::GetSettingCalendarResponseOfficialEventSettingInGameEventSettingRecentPlayGameTitlesInner>,
        other_game_titles: Vec<models::GetSettingCalendarResponseOfficialEventSettingInGameEventSettingRecentPlayGameTitlesInner>,
        show_until_play_next_button: bool,
    ) -> GetSettingCalendarResponseOfficialEventSettingInGameEventSetting {
        GetSettingCalendarResponseOfficialEventSettingInGameEventSetting {
            enabled,
            recent_play_game_titles,
            past_play_game_titles,
            other_game_titles,
            show_until_play_next_button,
        }
    }
}
