/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEventSchedule {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    #[serde(rename = "event_schedule")]
    pub event_schedule: Box<models::UserEventSchedule>,
}

impl GetEventSchedule {
    pub fn new(
        user_basic_info: models::UserBasicInfo,
        event_schedule: models::UserEventSchedule,
    ) -> GetEventSchedule {
        GetEventSchedule {
            user_basic_info: Box::new(user_basic_info),
            event_schedule: Box::new(event_schedule),
        }
    }
}
