/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFavoriteIpOptionsResponse {
    #[serde(rename = "favorite_ip_options")]
    pub favorite_ip_options: Vec<models::GetFavoriteIpOptionsResponseFavoriteIpOptionsInner>,
}

impl GetFavoriteIpOptionsResponse {
    pub fn new(
        favorite_ip_options: Vec<models::GetFavoriteIpOptionsResponseFavoriteIpOptionsInner>,
    ) -> GetFavoriteIpOptionsResponse {
        GetFavoriteIpOptionsResponse {
            favorite_ip_options,
        }
    }
}
