/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSettingQrResponse {
    /// チェックイン用QRコードに含めるURL
    #[serde(rename = "qr_code_param")]
    pub qr_code_param: String,
    /// チェックイン用QRコードの有効期限
    #[serde(rename = "expired_at")]
    pub expired_at: i64,
}

impl GetSettingQrResponse {
    pub fn new(qr_code_param: String, expired_at: i64) -> GetSettingQrResponse {
        GetSettingQrResponse {
            qr_code_param,
            expired_at,
        }
    }
}
