/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetContentEvaluationsInner : コンテンツの評価
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContentEvaluationsInner {
    /// コンテンツの評価軸 1: 役に立つ 2: おもしろい 3: クール 4: キュート
    #[serde(rename = "evaluation_type")]
    pub evaluation_type: i64,
    /// 評価の割合(%)
    #[serde(rename = "percent")]
    pub percent: i64,
    /// ユーザが評価した評価軸かどうか
    #[serde(rename = "selected")]
    pub selected: bool,
}

impl GetContentEvaluationsInner {
    /// コンテンツの評価
    pub fn new(evaluation_type: i64, percent: i64, selected: bool) -> GetContentEvaluationsInner {
        GetContentEvaluationsInner {
            evaluation_type,
            percent,
            selected,
        }
    }
}
