/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSettingNotificationResponse {
    #[serde(rename = "notification_setting")]
    pub notification_setting: Box<models::GetSettingNotificationResponseNotificationSetting>,
}

impl GetSettingNotificationResponse {
    pub fn new(
        notification_setting: models::GetSettingNotificationResponseNotificationSetting,
    ) -> GetSettingNotificationResponse {
        GetSettingNotificationResponse {
            notification_setting: Box::new(notification_setting),
        }
    }
}
