/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetHiddenEventSchedules {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    #[serde(rename = "event_schedules", skip_serializing_if = "Option::is_none")]
    pub event_schedules: Option<Vec<models::UserEventSchedule>>,
    /// 次のページが存在するかどうか
    #[serde(rename = "exist_next_page", skip_serializing_if = "Option::is_none")]
    pub exist_next_page: Option<bool>,
}

impl GetHiddenEventSchedules {
    pub fn new(user_basic_info: models::UserBasicInfo) -> GetHiddenEventSchedules {
        GetHiddenEventSchedules {
            user_basic_info: Box::new(user_basic_info),
            event_schedules: None,
            exist_next_page: None,
        }
    }
}
