/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAnnouncementUnreadCount {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    /// 未読件数
    #[serde(rename = "count")]
    pub count: i64,
}

impl GetAnnouncementUnreadCount {
    pub fn new(user_basic_info: models::UserBasicInfo, count: i64) -> GetAnnouncementUnreadCount {
        GetAnnouncementUnreadCount {
            user_basic_info: Box::new(user_basic_info),
            count,
        }
    }
}
