/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAllCalendars {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    #[serde(rename = "calendars")]
    pub calendars: Vec<models::Calendar>,
}

impl GetAllCalendars {
    pub fn new(
        user_basic_info: models::UserBasicInfo,
        calendars: Vec<models::Calendar>,
    ) -> GetAllCalendars {
        GetAllCalendars {
            user_basic_info: Box::new(user_basic_info),
            calendars,
        }
    }
}
