/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetHomeAnnouncements {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    /// おしらせ
    #[serde(rename = "announcements")]
    pub announcements: Vec<models::UserAnnouncement>,
}

impl GetHomeAnnouncements {
    pub fn new(
        user_basic_info: models::UserBasicInfo,
        announcements: Vec<models::UserAnnouncement>,
    ) -> GetHomeAnnouncements {
        GetHomeAnnouncements {
            user_basic_info: Box::new(user_basic_info),
            announcements,
        }
    }
}
