/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNotifyEventSchedules {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    #[serde(rename = "event_schedules")]
    pub event_schedules: Vec<models::UserEventSchedule>,
}

impl GetNotifyEventSchedules {
    pub fn new(
        user_basic_info: models::UserBasicInfo,
        event_schedules: Vec<models::UserEventSchedule>,
    ) -> GetNotifyEventSchedules {
        GetNotifyEventSchedules {
            user_basic_info: Box::new(user_basic_info),
            event_schedules,
        }
    }
}
