/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAnnouncements {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    /// おしらせの総数
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i64>,
    /// おしらせ
    #[serde(rename = "announcements")]
    pub announcements: Vec<models::UserAnnouncement>,
}

impl GetAnnouncements {
    pub fn new(
        user_basic_info: models::UserBasicInfo,
        announcements: Vec<models::UserAnnouncement>,
    ) -> GetAnnouncements {
        GetAnnouncements {
            user_basic_info: Box::new(user_basic_info),
            total_count: None,
            announcements,
        }
    }
}
