/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWidgets {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    /// キャラクター画像（大）のURL
    #[serde(rename = "large_image_url", skip_serializing_if = "Option::is_none")]
    pub large_image_url: Option<String>,
    /// キャラクター画像（中）のURL
    #[serde(rename = "medium_image_url", skip_serializing_if = "Option::is_none")]
    pub medium_image_url: Option<String>,
}

impl GetWidgets {
    pub fn new(user_basic_info: models::UserBasicInfo) -> GetWidgets {
        GetWidgets {
            user_basic_info: Box::new(user_basic_info),
            large_image_url: None,
            medium_image_url: None,
        }
    }
}
