/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPersonalizedContentsContentsInner {
    #[serde(rename = "content")]
    pub content: Box<models::UserContent>,
    /// 枠の種類  こちらから確認できます https://github.dena.jp/deepen/deepen-server/blob/develop/personalize/domain/model/selected_content.go 100: Extra (号外) 101: オンボーディング枠
    #[serde(rename = "section_type")]
    pub section_type: i32,
    /// スコア
    #[serde(rename = "score")]
    pub score: f64,
}

impl GetPersonalizedContentsContentsInner {
    pub fn new(
        content: models::UserContent,
        section_type: i32,
        score: f64,
    ) -> GetPersonalizedContentsContentsInner {
        GetPersonalizedContentsContentsInner {
            content: Box::new(content),
            section_type,
            score,
        }
    }
}
