/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSettingNotificationResponseNotificationSetting {
    /// 通知が有効かどうか. デフォルトfalse
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// ピックアップニュースを受信するかどうか. デフォルトtrue
    #[serde(
        rename = "pickup_notification_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub pickup_notification_enabled: Option<bool>,
    /// 毎日のお知らせを受信するかどうか. デフォルトtrue
    #[serde(
        rename = "daily_notification_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub daily_notification_enabled: Option<bool>,
    /// 毎日のお知らせを受信する時刻(0 ~ 23)
    #[serde(
        rename = "daily_notification_time",
        skip_serializing_if = "Option::is_none"
    )]
    pub daily_notification_time: Option<i64>,
    /// カレンダー通知を受信するかどうか. デフォルトtrue
    #[serde(
        rename = "calendar_notification_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub calendar_notification_enabled: Option<bool>,
    /// あなたへのお知らせを受信するかどうか. デフォルトtrue
    #[serde(
        rename = "personalized_notification_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub personalized_notification_enabled: Option<bool>,
}

impl GetSettingNotificationResponseNotificationSetting {
    pub fn new(enabled: bool) -> GetSettingNotificationResponseNotificationSetting {
        GetSettingNotificationResponseNotificationSetting {
            enabled,
            pickup_notification_enabled: None,
            daily_notification_enabled: None,
            daily_notification_time: None,
            calendar_notification_enabled: None,
            personalized_notification_enabled: None,
        }
    }
}
