/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPersonalizedContents {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    /// コンテンツ
    #[serde(rename = "contents")]
    pub contents: Vec<models::GetPersonalizedContentsContentsInner>,
}

impl GetPersonalizedContents {
    pub fn new(
        user_basic_info: models::UserBasicInfo,
        contents: Vec<models::GetPersonalizedContentsContentsInner>,
    ) -> GetPersonalizedContents {
        GetPersonalizedContents {
            user_basic_info: Box::new(user_basic_info),
            contents,
        }
    }
}
