/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAvailableGameTitleTags {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    #[serde(rename = "game_title_tags")]
    pub game_title_tags: Vec<models::Tag>,
    /// ソフトに紐づくプラットフォームのタグ
    #[serde(rename = "platform_tags")]
    pub platform_tags: Vec<models::Tag>,
}

impl GetAvailableGameTitleTags {
    pub fn new(
        user_basic_info: models::UserBasicInfo,
        game_title_tags: Vec<models::Tag>,
        platform_tags: Vec<models::Tag>,
    ) -> GetAvailableGameTitleTags {
        GetAvailableGameTitleTags {
            user_basic_info: Box::new(user_basic_info),
            game_title_tags,
            platform_tags,
        }
    }
}
