/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUser {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    #[serde(rename = "user")]
    pub user: Box<models::User>,
}

impl GetUser {
    pub fn new(user_basic_info: models::UserBasicInfo, user: models::User) -> GetUser {
        GetUser {
            user_basic_info: Box::new(user_basic_info),
            user: Box::new(user),
        }
    }
}
