/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSettingCalendarResponseOfficialEventSetting : 任天堂イベントの設定に関わる情報
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSettingCalendarResponseOfficialEventSetting {
    /// Nintendo Directが有効かどうか
    #[serde(rename = "nintendo_direct_enabled")]
    pub nintendo_direct_enabled: bool,
    /// Nintendo Switch Onlineに加入しているかどうか
    #[serde(rename = "is_nintendo_switch_online_active")]
    pub is_nintendo_switch_online_active: bool,
    /// Nintendo Switch Onlineが有効かどうか
    #[serde(rename = "nintendo_switch_online_enabled")]
    pub nintendo_switch_online_enabled: bool,
    #[serde(rename = "in_game_event_setting")]
    pub in_game_event_setting:
        Box<models::GetSettingCalendarResponseOfficialEventSettingInGameEventSetting>,
    /// ソフトの発売日／配信日（体験版含む）が有効かどうか
    #[serde(rename = "new_release_enabled")]
    pub new_release_enabled: bool,
    /// おすすめイベントが有効かどうか
    #[serde(rename = "personalized_enabled")]
    pub personalized_enabled: bool,
    /// その他のイベントが有効化どうか
    #[serde(rename = "other_event_enabled")]
    pub other_event_enabled: bool,
}

impl GetSettingCalendarResponseOfficialEventSetting {
    /// 任天堂イベントの設定に関わる情報
    pub fn new(
        nintendo_direct_enabled: bool,
        is_nintendo_switch_online_active: bool,
        nintendo_switch_online_enabled: bool,
        in_game_event_setting: models::GetSettingCalendarResponseOfficialEventSettingInGameEventSetting,
        new_release_enabled: bool,
        personalized_enabled: bool,
        other_event_enabled: bool,
    ) -> GetSettingCalendarResponseOfficialEventSetting {
        GetSettingCalendarResponseOfficialEventSetting {
            nintendo_direct_enabled,
            is_nintendo_switch_online_active,
            nintendo_switch_online_enabled,
            in_game_event_setting: Box::new(in_game_event_setting),
            new_release_enabled,
            personalized_enabled,
            other_event_enabled,
        }
    }
}
