/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRequiredCalendarsCalendarsInner {
    /// 日付
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "calendar")]
    pub calendar: Box<models::Calendar>,
}

impl GetRequiredCalendarsCalendarsInner {
    pub fn new(date: String, calendar: models::Calendar) -> GetRequiredCalendarsCalendarsInner {
        GetRequiredCalendarsCalendarsInner {
            date,
            calendar: Box::new(calendar),
        }
    }
}
