/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InternalServerError500Response {
    /// - [UNKNOWN_SERVER_ERROR] DBからの取得、保存に失敗した時などの予期せぬエラーです - [NA_API_ERROR] NA APIでエラーが発生しました - [BAAS_API_ERROR] BaaS APIでエラーが発生しました - [YATA_API_ERROR] YATA APIでエラーが発生しました
    #[serde(rename = "error_code", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<String>,
    /// - RECOVERABLE   - ユーザが操作しなおす、最新のデータを取得しなおすことで直る可能性のあるエラー     - 入力された値が不正       - 必須項目が未入力       - 最大文字数を超えている       - など     - コンフリクト       - すでに存在するデータを新規に作成しようとしている       - バージョンの古いデータを更新しようとしている       - など - FATAL   - コードの修正が必要かもしれないエラー - TEMPORARY   - 一時的なエラー - UNAUTHORIZED   - リクエストは正常に受け付けたが、認証できない場合のエラー   - クライアントがこのエラーを受け取った場合、直ちに現在のセッションを破棄しなければならない
    #[serde(rename = "error_type", skip_serializing_if = "Option::is_none")]
    pub error_type: Option<String>,
}

impl InternalServerError500Response {
    pub fn new() -> InternalServerError500Response {
        InternalServerError500Response {
            error_code: None,
            error_type: None,
        }
    }
}
