/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Maintenance503ResponseErrorExtra {
    /// メンテナンスメッセージ
    #[serde(rename = "maintenance_message")]
    pub maintenance_message: String,
    /// メンテナンス終了予定時刻、終了時刻が設定されていない場合フィールドごと無くなります。
    #[serde(
        rename = "maintenance_endtime",
        skip_serializing_if = "Option::is_none"
    )]
    pub maintenance_endtime: Option<i64>,
}

impl Maintenance503ResponseErrorExtra {
    pub fn new(maintenance_message: String) -> Maintenance503ResponseErrorExtra {
        Maintenance503ResponseErrorExtra {
            maintenance_message,
            maintenance_endtime: None,
        }
    }
}
