/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostPushToken {
    /// BaaSが発行したDeviceAccountのID
    #[serde(rename = "device_account_id")]
    pub device_account_id: String,
    /// FCM の Push Token
    #[serde(rename = "token")]
    pub token: String,
}

impl PostPushToken {
    pub fn new(device_account_id: String, token: String) -> PostPushToken {
        PostPushToken {
            device_account_id,
            token,
        }
    }
}
