/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostAuthLoginRequest {
    /// SD BaaSで発行されたUserのID Token
    #[serde(rename = "id_token")]
    pub id_token: String,
    /// NSAで発行されたNAのID Token
    #[serde(rename = "na_id_token")]
    pub na_id_token: String,
    /// SD BaaSで発行されたDeviceAccountのID
    #[serde(rename = "device_account_id")]
    pub device_account_id: String,
}

impl PostAuthLoginRequest {
    pub fn new(
        id_token: String,
        na_id_token: String,
        device_account_id: String,
    ) -> PostAuthLoginRequest {
        PostAuthLoginRequest {
            id_token,
            na_id_token,
            device_account_id,
        }
    }
}
