/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostAuthRefreshRequest {
    /// リフレッシュトークン
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
    /// SD BaaSで発行されたDeviceAccountのID
    #[serde(rename = "device_account_id")]
    pub device_account_id: String,
}

impl PostAuthRefreshRequest {
    pub fn new(refresh_token: String, device_account_id: String) -> PostAuthRefreshRequest {
        PostAuthRefreshRequest {
            refresh_token,
            device_account_id,
        }
    }
}
