/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostAuthRefreshResponse {
    /// 新しいアクセストークン
    #[serde(rename = "access_token")]
    pub access_token: String,
}

impl PostAuthRefreshResponse {
    pub fn new(access_token: String) -> PostAuthRefreshResponse {
        PostAuthRefreshResponse { access_token }
    }
}
