/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Premiere {
    /// プレミア公開ID
    #[serde(rename = "premiere_id")]
    pub premiere_id: String,
    /// コンテンツID
    #[serde(rename = "content_id")]
    pub content_id: String,
    /// プレミア公開URL
    #[serde(rename = "premiere_url")]
    pub premiere_url: String,
    /// プレミア公開後に表示する動画URL
    #[serde(rename = "content_movie_url")]
    pub content_movie_url: String,
    /// プレミア公開の待機画面(WebView)URL
    #[serde(rename = "waiting_screen_url")]
    pub waiting_screen_url: String,
    /// プレミア公開映像再生開始前に表示する蓋絵画像URL
    #[serde(rename = "video_poster_before_start_url")]
    pub video_poster_before_start_url: String,
    /// プレミア公開映像再生終了後に表示する蓋絵画像URL
    #[serde(rename = "video_poster_after_end_url")]
    pub video_poster_after_end_url: String,
    /// URLを開く際に必要なCDNのヘッダートークン
    #[serde(rename = "cdn_header_token")]
    pub cdn_header_token: String,
    /// プレミア公開の映像開始日時、映像を流して待機画面を終了する
    #[serde(rename = "premiere_stream_started_at")]
    pub premiere_stream_started_at: i64,
    /// プレミア公開開始日時、クライアントで残時間表示のために利用
    #[serde(rename = "premiere_started_at")]
    pub premiere_started_at: i64,
    /// プレミア公開終了日時
    #[serde(rename = "premiere_ended_at")]
    pub premiere_ended_at: i64,
    /// プレミア公開のVOD配信日時
    #[serde(rename = "premiere_vod_started_at")]
    pub premiere_vod_started_at: i64,
}

impl Premiere {
    pub fn new(
        premiere_id: String,
        content_id: String,
        premiere_url: String,
        content_movie_url: String,
        waiting_screen_url: String,
        video_poster_before_start_url: String,
        video_poster_after_end_url: String,
        cdn_header_token: String,
        premiere_stream_started_at: i64,
        premiere_started_at: i64,
        premiere_ended_at: i64,
        premiere_vod_started_at: i64,
    ) -> Premiere {
        Premiere {
            premiere_id,
            content_id,
            premiere_url,
            content_movie_url,
            waiting_screen_url,
            video_poster_before_start_url,
            video_poster_after_end_url,
            cdn_header_token,
            premiere_stream_started_at,
            premiere_started_at,
            premiere_ended_at,
            premiere_vod_started_at,
        }
    }
}
