/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutSettingCalendarRequestOfficialEventSettingInGameEventSetting : ゲーム内イベントに関連するイベントの設定
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutSettingCalendarRequestOfficialEventSettingInGameEventSetting {
    /// ゲーム内のイベントが有効かどうか
    #[serde(rename = "enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<Option<bool>>,
    /// ゲームタイトルごとの設定
    #[serde(rename = "game_titles", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub game_titles: Option<Option<Vec<models::PutSettingCalendarRequestOfficialEventSettingInGameEventSettingGameTitlesInner>>>,
}

impl PutSettingCalendarRequestOfficialEventSettingInGameEventSetting {
    /// ゲーム内イベントに関連するイベントの設定
    pub fn new() -> PutSettingCalendarRequestOfficialEventSettingInGameEventSetting {
        PutSettingCalendarRequestOfficialEventSettingInGameEventSetting {
            enabled: None,
            game_titles: None,
        }
    }
}
