/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutSettingFavoriteIpsRequest {
    #[serde(rename = "favorite_ips")]
    pub favorite_ips: Vec<i64>,
}

impl PutSettingFavoriteIpsRequest {
    pub fn new(favorite_ips: Vec<i64>) -> PutSettingFavoriteIpsRequest {
        PutSettingFavoriteIpsRequest { favorite_ips }
    }
}
