/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutSettingCalendarRequestOfficialEventSettingInGameEventSettingGameTitlesInner {
    /// ゲームタイトルID
    #[serde(rename = "game_title_id")]
    pub game_title_id: String,
    /// ゲーム内イベントが有効かどうか
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// 表示がOFFになる期間 1: 設定しない(無期限) 2: 次にプレイする時まで 3: 30日間
    #[serde(rename = "display_off_term_type")]
    pub display_off_term_type: i64,
}

impl PutSettingCalendarRequestOfficialEventSettingInGameEventSettingGameTitlesInner {
    pub fn new(
        game_title_id: String,
        display_off_term_type: i64,
    ) -> PutSettingCalendarRequestOfficialEventSettingInGameEventSettingGameTitlesInner {
        PutSettingCalendarRequestOfficialEventSettingInGameEventSettingGameTitlesInner {
            game_title_id,
            enabled: None,
            display_off_term_type,
        }
    }
}
