/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutSettingCalendarRequestOfficialEventSetting : 任天堂イベントの設定に関わる情報
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutSettingCalendarRequestOfficialEventSetting {
    /// Nintendo Directが有効かどうか
    #[serde(
        rename = "nintendo_direct_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub nintendo_direct_enabled: Option<Option<bool>>,
    /// Nintendo Switch Onlineが有効かどうか
    #[serde(
        rename = "nintendo_switch_online_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub nintendo_switch_online_enabled: Option<Option<bool>>,
    #[serde(
        rename = "in_game_event_setting",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub in_game_event_setting: Option<
        Option<Box<models::PutSettingCalendarRequestOfficialEventSettingInGameEventSetting>>,
    >,
    /// ソフトの発売日／配信日（体験版含む）が有効かどうか
    #[serde(
        rename = "new_release_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub new_release_enabled: Option<Option<bool>>,
    /// おすすめイベントが有効かどうか
    #[serde(
        rename = "personalized_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub personalized_enabled: Option<Option<bool>>,
    /// その他のイベントが有効化どうか
    #[serde(
        rename = "other_event_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub other_event_enabled: Option<Option<bool>>,
}

impl PutSettingCalendarRequestOfficialEventSetting {
    /// 任天堂イベントの設定に関わる情報
    pub fn new() -> PutSettingCalendarRequestOfficialEventSetting {
        PutSettingCalendarRequestOfficialEventSetting {
            nintendo_direct_enabled: None,
            nintendo_switch_online_enabled: None,
            in_game_event_setting: None,
            new_release_enabled: None,
            personalized_enabled: None,
            other_event_enabled: None,
        }
    }
}
