/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchContents {
    #[serde(rename = "user_basic_info")]
    pub user_basic_info: Box<models::UserBasicInfo>,
    /// コンテンツ
    #[serde(rename = "contents")]
    pub contents: Vec<models::UserContent>,
    /// ヘッダー画像のURL ソフトやIPでない検索の場合は空になることもあります
    #[serde(rename = "search_header_image_url")]
    pub search_header_image_url: String,
    /// 検索画面のタグのカラー
    #[serde(rename = "search_view_tag_color")]
    pub search_view_tag_color: String,
    /// 検索画面のヘッダーに表示するタグ名
    #[serde(rename = "tag_name")]
    pub tag_name: String,
    #[serde(rename = "all_content_ids")]
    pub all_content_ids: Vec<String>,
    /// コンテンツに含まれるコンテンツ分類のリスト [deprecated] narrow_down_tags を使ってください
    #[serde(rename = "content_category_tags")]
    pub content_category_tags: Vec<models::Tag>,
    /// 絞り込みUIに表示する項目のリスト
    #[serde(rename = "narrow_down_tags")]
    pub narrow_down_tags: Vec<models::Tag>,
}

impl SearchContents {
    pub fn new(
        user_basic_info: models::UserBasicInfo,
        contents: Vec<models::UserContent>,
        search_header_image_url: String,
        search_view_tag_color: String,
        tag_name: String,
        all_content_ids: Vec<String>,
        content_category_tags: Vec<models::Tag>,
        narrow_down_tags: Vec<models::Tag>,
    ) -> SearchContents {
        SearchContents {
            user_basic_info: Box::new(user_basic_info),
            contents,
            search_header_image_url,
            search_view_tag_color,
            tag_name,
            all_content_ids,
            content_category_tags,
            narrow_down_tags,
        }
    }
}
