/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateEventScheduleUserSettings {
    /// 通知するかどうか
    #[serde(
        rename = "enable_notification",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub enable_notification: Option<Option<bool>>,
    /// 何秒前に通知するのか。非通知の場合は 0。
    #[serde(
        rename = "notify_before_seconds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notify_before_seconds: Option<Option<i64>>,
    /// 表示・非表示
    #[serde(
        rename = "is_hidden",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_hidden: Option<Option<bool>>,
}

impl UpdateEventScheduleUserSettings {
    pub fn new() -> UpdateEventScheduleUserSettings {
        UpdateEventScheduleUserSettings {
            enable_notification: None,
            notify_before_seconds: None,
            is_hidden: None,
        }
    }
}
