/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAnnouncement {
    /// おしらせID
    #[serde(rename = "id")]
    pub id: String,
    /// 既読かどうか
    #[serde(rename = "is_read")]
    pub is_read: bool,
    /// 既読した時刻のunix time stamp
    #[serde(rename = "read_at")]
    pub read_at: i64,
    #[serde(rename = "announcement")]
    pub announcement: Box<models::Announcement>,
    /// 未読ランプを表示するかどうか
    #[serde(rename = "show_unread_lamp")]
    pub show_unread_lamp: bool,
}

impl UserAnnouncement {
    pub fn new(
        id: String,
        is_read: bool,
        read_at: i64,
        announcement: models::Announcement,
        show_unread_lamp: bool,
    ) -> UserAnnouncement {
        UserAnnouncement {
            id,
            is_read,
            read_at,
            announcement: Box::new(announcement),
            show_unread_lamp,
        }
    }
}
