/*
 * Deepen API
 *
 * Deepen API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// Deepen独自のユーザID
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "favorite_ips")]
    pub favorite_ips: Vec<i64>,
    /// 好きなIPを選択しているかどうか 一度もupdateFavoriteIpsを叩いていない時のみfalseになります
    #[serde(rename = "is_selected_favorite_ips")]
    pub is_selected_favorite_ips: bool,
}

impl User {
    pub fn new(user_id: String, favorite_ips: Vec<i64>, is_selected_favorite_ips: bool) -> User {
        User {
            user_id,
            favorite_ips,
            is_selected_favorite_ips,
        }
    }
}
